# TODO: Should terraform generate the secret?
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: "${namespace}"
type: Opaque
data:
  password: UGFzc3dvcmQkMTIzNDU2 # Password$123456
  admin-password: UGFzc3dvcmQkMTIzNDU2 # Password$123456