# At minimum, headless service for mysql is required to provide network DNS identity for pods as they are referenced in
# the clustering configuration.
# ClusterIP service is required so mysql-router can connect to any running instance to bootstrap the config instead of
# hard coding any instance as the one that provides bootstrap configuration
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: "${namespace}"
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  type: ClusterIP
  # clusterIP: None
  selector:
    app: mysql
