apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-exporter
  namespace: "${namespace}"
  labels:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-25.1.5
    app.kubernetes.io/component: cluster-metrics
automountServiceAccountToken: true
