
# Source: app/charts/kafka/templates/metrics/jmx-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-jmx-metrics
  namespace: "${namespace}"
  labels:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-25.1.5
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/path: /
    prometheus.io/port: '5556'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http-metrics
      port: 5556
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: kafka
