
# Source: app/charts/kafka/templates/metrics/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-metrics
  namespace: "${namespace}"
  labels:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-25.1.5
    app.kubernetes.io/component: cluster-metrics
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '9308'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http-metrics
      port: 9308
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: cluster-metrics
