
# Source: app/charts/kafka/templates/metrics/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: "${namespace}"
  labels:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-25.1.5
    app.kubernetes.io/component: cluster-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/name: kafka
      app.kubernetes.io/component: cluster-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kafka
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kafka
        helm.sh/chart: kafka-25.1.5
        app.kubernetes.io/component: cluster-metrics
    spec:

      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: kafka
                    app.kubernetes.io/name: kafka
                    app.kubernetes.io/component: cluster-metrics
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:

      securityContext:
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: kafka-exporter
      enableServiceLinks: true
      containers:
        - name: kafka-exporter
          image: bitnami/kafka-exporter:1.6.0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
          command:
            - bash
          args:
            - -ce
            - |
              kafka_exporter \
              --kafka.server=kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092 \
              --kafka.server=kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092 \
              --kafka.server=kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092 \
              --sasl.enabled \
              --sasl.username=$SASL_USERNAME \
              --sasl.password=$SASL_USER_PASSWORD \
              --sasl.mechanism=scram-sha512 \
              --web.listen-address=:9308
          env:
            - name: SASL_USERNAME
              value: "user1"
            - name: SASL_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-user-passwords
                  key: system-user-password
          ports:
            - name: metrics
              containerPort: 9308
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: "2Gi"
            requests:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: "2Gi"
          volumeMounts:
      volumes:
