
# Source: app/templates/podmonitoring.yaml
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: kafka
  namespace: "${namespace}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafka
  endpoints:
  - port: metrics
    interval: 30s
