apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-start
  namespace: ${namespace}
spec:
  suspend: true
  parallelism: 1
  completions: 1
  template:
    spec:
      containers:
      - name: redis-cluster-start
        image: ${image}
        command:
        - redis-cli
        - --cluster
        - create
        %{~ for n in nodes ~}
        - ${n}
        %{~ endfor ~}
        - --cluster-replicas
        - 1
        - --cluster-yes
      restartPolicy: Never
