name: Run CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-ci:
    name: "Test CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          
      - run: |
          ls
          git status
